### ISSUE TITLE
"wrong constant name rootQuery" errors after updating to 0.10.0

### ISSUE THREAD

**Issue by complex857** [github/graphql-client#105]
After updating to 0.10.0 I've started getting the following errors:

```
wrong constant name rootQuery

Trace:
graphql-client (0.10.0) lib/graphql/client/schema.rb:51:in `const_set'
graphql-client (0.10.0) lib/graphql/client/schema.rb:51:in `block in generate'
graphql-client (0.10.0) lib/graphql/client/schema.rb:47:in `generate'
graphql-client (0.10.0) lib/graphql/client.rb:95:in `initialize'
...
```
From what I can tell with a debugger, it seems that the code expects a constant named `rootQuery` to exists but it doesn't.
If i check the result of `schema.types` in the here: `lib/graphql/client/schema.rb @ line 39 GraphQL::Client::Schema.generate` I can see that stuff like `Long`, `Int`, `Float` and the others have a const defined for them but not `rootQuery`:

![screen shot 2017-05-17 at 12 16 18](https://cloud.githubusercontent.com/assets/131617/26149471/b1da7c9c-3afa-11e7-8806-1150f736c0c4.png)

The same code with the version 0.9.0 works without issues.

**Comment by rmosolgo** [comment]
Perhaps there is a type in your schema with the name `"rootQuery"`? I think it should be called `RootQuery` (or even `Query`, which is the most common name for the root query type). 

I think graphql-client builds classes for each type, but `rootQuery` isn't a valid class name: 

```
irb(main):001:0> class rootQuery; end
SyntaxError: (irb):1: class/module name must be CONSTANT
class rootQuery; end
                ^
```

**Comment by complex857** [comment]
Ah, I see, thats it!
So these things have to conform to ruby's constant naming conventions (the backend is implemented in java, too many departments here 😅 )

Thank you for the prompt response!
