### ISSUE TITLE
Question Regarding Enum Type in the schema

### ISSUE THREAD

**Issue by asheynkman** [github/graphql-client#107]
Hi there,

 I'm trying to load schema from the generated scheme file and keep getting exception . 

from /Users/aleks/.rvm/gems/ruby-2.3.3/gems/graphql-client-0.11.0/lib/graphql/client/schema/enum_type.rb:32:in `const_set'

Is there any well know issues with definition of the Enum Types?

HTTPAdapter = GraphQL::Client::HTTP.new("https://127.0.0,1:3000/graphql") do
    def headers(token)
      {
        "Authorization" => "Bearer #{token}"
      }
    end
  end

  Client = GraphQL::Client.new(
    schema: Application.root.join("db/schema.json").to_s,
    execute: HTTPAdapter
  )
  Application.config.graphql.client = Client

Thanks

**Comment by josh** [comment]
I think this error message could be better. Do any enums exist in the schema that are lowercase instead of the traditional uppercase style.

**Comment by mitnal** [comment]
Hi, I ran into the same problem. My enum type and name is uppercase but the values are lowercase. `unreadable` is one of my values.

The schema works without problems in GraphiQL.

```
client/schema/enum_type.rb:32:in `const_set': wrong constant name unreadable (NameError)
```

**Comment by joffotron** [comment]
Same issue for me too, our enum _values_ are in lowercase:

```
bundle/gems/graphql-client-0.11.1/lib/graphql/client/schema/enum_type.rb:32:in `const_set': wrong constant name individual (NameError)
	from /bundle/gems/graphql-client-0.11.1/lib/graphql/client/schema/enum_type.rb:32:in `block in initialize'
	from /bundle/gems/graphql-client-0.11.1/lib/graphql/client/schema/enum_type.rb:25:in `each'
	from /bundle/gems/graphql-client-0.11.1/lib/graphql/client/schema/enum_type.rb:25:in `initialize'
```

**Comment by mitnal** [comment]
If you have control over the server side and are using http://graphql-ruby.org an easy way to map enum types is to use the `value` keyword:

```
value('SCREAMING_CASE_NAMES', 'Some description.', value: 'screaming_case_names')
```

But be aware that this **changes the schema**! We could only do this because we just started with our GraphQL Api.

FYI:
> By convention, enum names are SCREAMING_CASE_NAMES, but other identifiers are supported too.
-- [GraphQL - EnumType](http://www.rubydoc.info/gems/graphql/1.6.3/GraphQL/EnumType)

**Comment by joffotron** [comment]
In our case, we managed to change the server values (and update our clients to match). Had this been a public API, this would have been awkward.

I would suggest that the client library should be permissive, and accept the lower-case values (the spec doesn't mandate them). Maybe a warning message would be appropriate here

**Comment by asheynkman** [comment]
I endup using "graphql-client", "0.2.3" seems like work , but I'm sure there is a better option
