### ISSUE TITLE
What is the difference between this and rmosolgo/graphql-ruby?

### ISSUE THREAD

**Issue by NickHeiner** [github/graphql-client#113]
A note in the README says:

> ## See Also
> 
> * [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) gem which implements 80% of what this library provides. ❤️ [@rmosolgo](https://github.com/rmosolgo)

So why does this repo exist? What's the extra 20%? How do I figure out which of the two libraries is right for me? :smile:

**Comment by nakajima** [comment]
The graphql-ruby gem is primarily for exposing a GraphQL API in your app (it also includes a parser for GraphQL which this gem makes use of). This gem is for consuming a GraphQL API.

**Comment by NickHeiner** [comment]
Ah, that makes sense. Thanks!
