### ISSUE TITLE
Schema loading in a client Rails app

### ISSUE THREAD

**Issue by snarfmason** [github/graphql-client#115]
We're using a Rails app as a GraphQL client, using the `GraphQL::Client` gem. We are building the GraphQL server in Elixir/Absinthe, and we're working on synching the GraphQL schema.

The docs for that suggest that we should load the schema into a constant like:

```ruby
  # Fetch latest schema on init, this will make a network request
  Schema = GraphQL::Client.load_schema(HTTP)
``` 

But that HTTP request, which happens during Rails startup, might fail, preventing Rails app startup. The only example our team has found of using Rails as a GraphQL client, does not load the Schema over HTTP, it just loads it from a file.
- https://github.com/github/github-graphql-rails-example/blob/master/config/application.rb
  
We'd like to fetch the schema over HTTP, as the `GraphQL::Client` docs suggest doing, so that we don't need to update a schema file in the Rails client app whenever we change the Schema on our server. The only way that this seems to work is using variables for the parsed queries, but that functionality is deprecated in `GraphQL::Client`.

Is there a recommended best practice on how to use `GraphQL::Client` in this situation?

**Comment by envygeeks** [comment]
Personally what we do in this situation is always load from a schema file if it exists and only fetch from HTTP if it doesn't exist, and then there is a rake task that gets ran outside of that for the schema to get pushed up into the repository with the rest.

```ruby
require "graphql/client"

module AppName
  module Helpers
    module GraphQL
      module_function

      def fetch_schema(endpoint)
        path = GQLDir.join("github.json").to_s
        return GraphQL::Client.load_schema(path) if File.file?(path)
        GraphQL::Client.dump_schema(endpoint, path)
      end
    end
  end
end
```

At that point we have a rake task that removes the schema file, and runs this method resulting in an updated schema whenever we feel like updating it.

**Comment by sepehr500** [comment]
Can I make queries without pulling in the schema? I really do not want the client to be dependent on the back end like that, an I am fine with validation being done on the server side.

**Comment by josh** [comment]
It's highly recommended to keep a schema text file checked into your repository. I'd suggest pointing to that rather than fetching it from HTTP.

**Comment by krishnarohitreddy** [comment]
@josh why are we loading schema for a request, like @sepehr500 said can't we make queries without schema?

**Comment by la-jamesh** [comment]
I also find it very very strange to not (at the very least) provide a configuration option to not load the schema every time the client is configured. Very odd. I haven't seen this in any other GQL library.

**Comment by envygeeks** [comment]
I don't think people ever really expected schema's as big as Github, hindsight will kill us all.
