### ISSUE TITLE
Proper documentation and examples can lead to errors with client.

### ISSUE THREAD

**Issue by envygeeks** [github/graphql-client#116]
When using the documentation and adapting its examples, and then using this library to parse the GraphQL, the documentation examples and the way this library behaves lead to errors.  Take for example: http://graphql.org/learn/queries/#fragments

```graphql
fragment repoFields on RepositoryConnection {
  totalCount
}

query PublicRepos($count: Int!, $user: String!, $after: String) {
  user(login: $user) {
    repositories(privacy: PUBLIC, first: $count, after: $after) {
      ...repoFields
    }
  }
}
```

This will lead to an error because of the way this library handles parsing: 

```
vendor/bundle/ruby/2.3.0/gems/graphql-client-0.11.3/lib/graphql/client.rb:222:in \
  `const_set': wrong constant name repoFields (NameError)
```

**Comment by josh** [comment]
Lowercase fragment names should be fixed as of https://github.com/github/graphql-client/commit/e4293ad2f4ab7758ca74b85ce10bd4c7cd9d7b96. Let me know if this is still an issue after that change.
