### ISSUE TITLE
Lowercase type names don't work

### ISSUE THREAD

**Issue by rf-** [github/graphql-client#123]
Since GraphQL::Client::Schema was added in v0.10.0, loading schemas that use lowercase type names has been broken, since lowercase names aren't valid constant names in Ruby (see #105, #107, #116). It's true that the examples in the GraphQL spec use uppercase letters for type names, but the spec doesn't actually require types to be uppercase, and it's a bummer to not be able to use this client with valid schemas that don't follow this convention.

I'm not clear on what these constants are actually used for, but would it maybe be possible to add an uppercase prefix to their names so that any valid GraphQL name will work?

**Comment by rf-** [comment]
After looking into it a bit more, it seems like adding a prefix wouldn't be a good solution since these names are user-facing, but maybe constantizing any names that aren't already valid constant names would be doable? That shouldn't be a breaking change since those names currently can't be used.

**Comment by josh** [comment]
Have you tried the latest release? This should be fixed as of https://github.com/github/graphql-client/commit/e4293ad2f4ab7758ca74b85ce10bd4c7cd9d7b96

**Comment by rf-** [comment]
I was using the latest release. It looks like that commit only applies to enums, right?

**Comment by rf-** [comment]
This is a little sloppy, but does seem to solve the problem on our schema: https://github.com/IFTTT/graphql-client/commit/824a091b8ea897ff62577ae7aa98336660f1e35f

If that seems like a reasonable approach to you, I could try to add some tests and work up a PR?
