### ISSUE TITLE
Consider moving to the graphql-ruby org?

### ISSUE THREAD

**Issue by dblock** [github/graphql-client#129]
Would maintainers consider moving this to a `graphql-ruby` org? Similar to https://github.com/slack-ruby or https://github.com/alexa-js or https://github.com/ruby-grape? I am happy to cheerlead. Owners will be all maintainers of this and other projects that would be the "founding members". It could become a home for projects such as this one and others, such as https://github.com/exAspArk/graphql-errors and https://github.com/ashkan18/graphlient.

This would make GraphQL ruby projects much more discoverable.

It seems to exist, https://github.com/graphql-ruby, but I am sure we can reclaim it from Github.

Related: https://github.com/rmosolgo/graphql-ruby/issues/1034

**Comment by josh** [comment]
It doesn't look like graphql-ruby will be moving, https://github.com/rmosolgo/graphql-ruby/issues/1034#issuecomment-339003113.
