### ISSUE TITLE
Expose HTTP Status to Response Object

### ISSUE THREAD

**Issue by weiqingtoh** [github/graphql-client#131]
There are instances where the http status of the response is required, and this is not made available through the `GraphQL::Client::Response` object. 

I would like to suggest that we pass this property to the response object, as it might be useful for the client side to know (and act on, for certain http status codes). 

Would like to see if this is the right approach, or have I missed out something in the documentation? I would be happy to try to make a PR for this if necessary. 

---

**Afternote**: There is a way to include this HTTP Status by writing a custom adapter. Adopting the adapter suggested in [Remote Queries](https://github.com/github/graphql-client/blob/master/guides/remote-queries.md), we can nest the HTTP Status in the response object itself: 

```ruby
require "faraday"

class FaradayAdapter
  def self.execute(document:, operation_name:, variables:, context:)
    response = Faraday.post("http://graphql-swapi.parseapp.com/", {
      "query" => document.to_query_string,
      "operationName" => operation_name,
      "variables" => variables
    })
    JSON.parse(response.body).merge(http_status: response.status)
  end
end
```

However, should we instead allow the response object to have a http status property?

**Comment by josh** [comment]
> I would like to suggest that we pass this property to the response object, as it might be useful for the client side to know (and act on, for certain http status codes).

I think this is something that is going to need to be adapted on a case by case basis. The GraphQL spec only covers HTTP as a transport but it could be other protocols. This library shouldn't be coupled to HTTP specifically.

I think your example code is probably what you'll want to use and adapt to whatever endpoint you are using.
