### ISSUE TITLE
Where are the mutations?

### ISSUE THREAD

**Issue by YakDriver** [github/graphql-client#145]
Using the GraphQL API, is it possible to do any of these tasks?

- Create/edit/delete repositories
- Create/edit/delete releases
- Create/update/merge pull requests
- Create tags
- Create files/blobs

We were discussing migrating to GraphQL from REST but without this functionality it seems premature. Being new to GraphQL, I want to make sure I'm not missing this functionality somewhere.

**Comment by josh** [comment]
This is a pretty general GraphQL question. I'd suggest reading [these docs on GraphQL mutations to get you started](http://graphql.org/learn/queries/#mutations). Thanks!

**Comment by YakDriver** [comment]
@josh  None of the functionality I mentioned is supported by GitHub's v4 API so without support on the backend, no amount of mutation understanding will help it work. 

@d12 provided this helpful response: https://platform.github.community/t/so-few-mutants-er-mutations/5681
