### ISSUE TITLE
'normalize_error_paths' doesn't handle nil values correctly

### ISSUE THREAD

**Issue by JordPWN** [github/graphql-client#146]
'normalize_error_paths' attempts to perform an each loop on nil values, resulting in an inaccurate error message. It will always output `exception undefined method 'each' for nil:NilClass`. 
```
".../gems/ruby-2.3.1/gems/graphql-client-0.12.3/lib/graphql/client/errors.rb:24:in `block in normalize_error_paths'"

result => {"data"=>nil,
 "errors"=>
  [{"path"=>nil,
    "locations"=>nil,
    "message"=>
     "The variables input contains a field name 'myField' that is not defined for input object type 'MyInput' "}]}
```

**Comment by josh** [comment]
Hmm, can you include a full trace. It looks like this should cover that case you are referring to.

https://github.com/github/graphql-client/blob/10de997d20692cc67b8081b31ef419974f62ba22/lib/graphql/client/errors.rb#L24

Thanks!

**Comment by halostatue** [comment]
This most certainly does not cover the case that @JordPWN reported, as `#fetch` only uses the default when the key is missing; the key `path` is not missing, but `nil` here. `{"path" => nil}.fetch("path", []) # => nil` This should be `(error["path"] || []).each` if you want this to work.

**Comment by erikdstock** [comment]
I actually just tracked a bug in something I'm working on down to the edge case @halostatue mentioned as well. Happy to make a PR if that works for yall!

**Comment by halostatue** [comment]
AppSync?
