### ISSUE TITLE
[feature] Ability to customize field selections to avoid making multiple similar queries

### ISSUE THREAD

**Issue by daemonsy** [github/graphql-client#15]
Hey Github, 

Thanks for the `graphql-client` gem. We're using it for two apps to communicate server to server and it's great so far. 

I liked the idea of making queries static as recommended in the `README`, one issue we foresee is that we might end up with multiple similar queries that negates the benefits of GQL. 

For example we have a query that parses phone numbers using [libphonenumber](https://github.com/googlei18n/libphonenumber) exposed over GraphQL. 

```ruby
PhoneNumberQuery = Graph::Client.parse <<~GQL
  query($number: String!) {
    parse_phone_number(number: $number {
      e164_format 
      international_format
      validity 
      carrier 
    }
  }
GQL
```

In an app, there are multiple times we want different field selections for different context. Making multiple static queries for these different context is hard, naming them is also pretty hard because of the similarity (e.g. bad names: `PhoneNumberQueryWithoutCarrier`, `PhoneNumberQueryE164Only`) 

Is there any consideration on the roadmap for adding a way to customize field selections on a parsed query or a way to have variants of a query?

**Comment by josh** [comment]
> Is there any consideration on the roadmap for adding a way to customize field selections on a parsed query or a way to have variants of a query?

One thing you may want to look into is the `@skip` and `@include` directives.

https://facebook.github.io/graphql/#sec--skip

**Comment by daemonsy** [comment]
Thanks for pointing to this. That's exactly it. Will submit PR to guides if we can get some nice patterns working with it.
