### ISSUE TITLE
Use-cases for disabling ImplicitlyFetchedFieldError

### ISSUE THREAD

**Issue by pushrax** [github/graphql-client#150]
Masking fields selected by fragments is an elegant approach to data isolation when composing data requirements of multiple components (in the general sense) into a single query. In this case, requiring usage of casting wrappers is reasonable and has clear value.

We've been trying out graphql-client for various server-to-server applications, where view code (the primary beneficiary of component isolation) is a secondary concern. When dealing with large APIs it can sometimes be appealing to factor shared fields of multiple queries into a fragment. These queries are executed and their response data is used in the same logical component. In this case the value of casting wrappers is less obvious and becomes tedious.

Is there a flaw in this observation, and if not would it make sense support configuring ImplicitlyFetchedFieldError either per-client or per-query or per-fragment? Interested in your thoughts @josh.

cc @jpittis @JackyChiu @swalkinshaw

**Comment by pushrax** [comment]
Yep, essentially that @rmosolgo.

**Comment by josh** [comment]
> These queries are executed and their response data is used in the same logical component. In this case the value of casting wrappers is less obvious and becomes tedious.

Yeah, in this case you can still use fragments but keep them in the same document. That avoids the whole *casting* thing as response wrappers are generated for the entire document. Something like this should work:

```
Document = SWAPI::Client.parse <<-'GRAPHQL'
  fragment on Foo {
    ...Bar
  }

  fragment on Bar {
    ...Baz
  }

  fragment on Baz {
    foo
  }
GRAPHQL
```

Hope that works, thanks!

**Comment by JackyChiu** [comment]
@josh Just to clarify, with that approach you wouldn't be able to reuse fragments across different documents?
