### ISSUE TITLE
Support for multiple queries in one request

### ISSUE THREAD

**Issue by jgayfer** [github/graphql-client#175]
As far as I can tell, this library does not support multiple queries/mutations in one request.

For additional context, I'm looking for something like the `Schema.multiplex` operation from `graphql-ruby`.

I could very well be missing something here. Can anyone confirm/deny this?

**Comment by george-norris-salesforce** [comment]
Wondering the same. I ended up doing them in one call..
``
{
  twbs: repository(owner: "twbs", name: "bootstrap-sass") {
    name
    primaryLanguage {
      name
    }
  }
  nookies: repository(owner: "", name: "") {
    name
    primaryLanguage {
      name
    }
  }
}
```
But it running into some limitations now..
`graphql-ruby` looks nice.

**Comment by raydefy** [comment]
This issue seems to be a non-issue or resolved. As seen in the post above, you need to alias each queries results. Notice in the example below, I have two queries. One returns `id` and the other returns `name`. 
```ruby
>> client.query(client.parse('{ q1: shop { name } q2: shop { id } }')).data.to_h
=> {"q1"=>{"name"=>"Shop 1"}, "q2"=>{"id"=>"gid://shopify/Shop/1"}}
>>
```

**Comment by jgayfer** [comment]
Thanks @raydefy, I'll close the issue.
