### ISSUE TITLE
How can I add a dynamic field to response?

### ISSUE THREAD

**Issue by ducnguyenhuy** [github/graphql-client#189]
I want to add a custom field to response. e.g: I'm querying the patients by practice_id and want  to add practice_id into patients list's response.

Please suggest me. Thanks a bunch.

**Comment by ducnguyenhuy** [comment]
@seejohnrun could you please help me on the above question? Thanks!

**Comment by seejohnrun** [comment]
Hey @ducnguyenhuy I'm not sure I quite understand the question but I'll try to provide some detail.  You'll want to add a field to the response type in the GraphQL object (server-side) in Ruby and then you'll be able to query that field to come back as part of the response to the client.

**Comment by ducnguyenhuy** [comment]
@seejohnrun Thanks for your reply.
I have same question as here https://stackoverflow.com/questions/49451234/is-it-possible-to-add-another-field-in-the-final-response-of-graphql-query

But I want to custom response from client, not server side. Do we have the option for `formatResponse` as in the shared link?
