### ISSUE TITLE
Error when loading Github's GraphQL schema

### ISSUE THREAD

**Issue by ianks** [github/graphql-client#207]
When attempting to load the Github's GraphQL schema over HTTP, we are getting this error:

```
GraphQL::Schema::InvalidTypeError: Field Query.organization's return type is invalid: field "pinnedRepositories" argument "affiliations" default value [#<GraphQL::Language::Nodes::Enum:0x0000558a4f24f2a0 @line=1, @col=34, @filename=nil, @name="OWNER">, #<GraphQL::Language::Nodes::Enum:0x0000558a4f24ec10 @line=1, @col=41, @filename=nil, @name="COLLABORATOR">] is not valid for type [RepositoryAffiliation] (Can't resolve enum RepositoryAffiliation for #<GraphQL::Language::Nodes::Enum:0x0000558a4f24f2a0 @line=1, @col=34, @filename=nil, @name="OWNER">)
```

Not sure if this is an issue with the client, but figured I should report it in case anyone else is experiencing this issue.

**Comment by laasem** [comment]
@ianks any update on this?

**Comment by 8geonirt** [comment]
@ianks  It was happening to me a few days ago, I am using the GraphQL endpoint from Github and I suddenly started getting those errors, I tried updating all the gems in my project and it started working again. I haven't had the time to search what was causing the issue. It would be great to know the root cause of that.

**Comment by laasem** [comment]
Same, worked for me when I updated to the latest master.

**Comment by ericyd** [comment]
That error indicates an issue with the Github schema, not the client. It shows that the default value for the argument `affiliations` of the field `pinnedRepositories` is not a valid member of the Enum defined for that field. Although its not super human-readable, it isn't an issue with the client, it was an issue with their schema.

However, you can see in the changelog that this field was removed from the schema on June 28. This is likely why it started working again.

https://developer.github.com/v4/changelog/#--graphql-schema-changes-for-2019-06-28

@rmosolgo I think this can also be closed.

**Comment by rmosolgo** [comment]
:+1: thanks
