### ISSUE TITLE
Is there a possibility to change the HTTP endpoint URL in runtime? (For Shopify apps)

### ISSUE THREAD

**Issue by tolgap** [github/graphql-client#208]
For Shopify Private Apps, you can have support for multiple Shopify Stores in a single App. All Stores have their own API endpoint, and their own API key.

I realize you can change the API key by using the HTTP context to change the headers. But I can't figure out how the change the endpoint URL. I don't even think its possible because the `HTTP` client has to be setup to be a constant.

**Comment by ericyd** [comment]
I believe the convention here would be to instantiate a new client for each endpoint. Is there a downside to this?

**Comment by tolgap** [comment]
@ericyd it would be because of these two issues:

https://github.com/Shopify/shopify_api/issues/511
https://github.com/Shopify/shopify_api/issues/510

Shopify's schema is absolutely enormous, so constant recreation is incredibly inefficient.

**Comment by ericyd** [comment]
Ah, makes sense. That is an interesting issue. I think you're right that this isn't possible with current architecture. Seems like a valid feature request though.

**Comment by RichardBlair** [comment]
Shopify has implemented a client which does caching and their client sets the headers and url dynamically at runtime. Probably can close this, although y'all definitely should connect with them. As @tolgap mentioned their Schema is insane.

**Comment by tolgap** [comment]
I can confirm that this is now a non-issue for me. ShopifyAPI's new GraphQL client setup is now cached, and URLs and access tokens are dynamic.
