### ISSUE TITLE
Are you planning to release a new version?

### ISSUE THREAD

**Issue by takkanm** [github/graphql-client#215]
I want to call `GraphQL::Client.dump_schema` with context. 
https://github.com/github/graphql-client/blob/master/lib/graphql/client.rb#L73

But, latest version(0.14.0) can't call with context.
https://github.com/github/graphql-client/blob/v0.14.0/lib/graphql/client.rb#L72

**Comment by ericyd** [comment]
@rmosolgo you can close this as of v0.15.0.

https://github.com/github/graphql-client/blob/v0.15.0/lib/graphql/client.rb#L72

**Comment by rmosolgo** [comment]
Thanks!

**Comment by takkanm** [comment]
Thank you!! 👍
