### ISSUE TITLE
How can I print a copy of all values and attributes from a query response?

### ISSUE THREAD

**Issue by Schwad** [github/graphql-client#221]
I am currently using this gem to access a third party Graphql Database. 

I need to print out all attributes and values from a returned query response. I could not find anything in standard documentation to support this (and of course `inspect` just yields `"#< attribute1=... attribute2=nil attribute3=hello>"` )

**What I want to produce is:**

```ruby
[
  "Attribute1: Value",
  "Attribute2: []",
  "Attribute3: nil"
]
```

The code I use, which works if there are not 'objects' in the response, is:

```ruby
@input = input
        (@input.public_methods - Object.public_methods).reject{|elem| [:to_h, :errors, :method_missing].include?(elem) || elem.to_s.include?('?')}.map{|elem| "#{elem.to_s.humanize}: #{@input.send(elem)}"}

#=>

[
  "Attribute1: Value",
  "Attribute2: []",
  "Attribute3: nil"
]
```

This essentially calls every public method on the object, sans `Object` public methods and also a few handpicked ones that aren't the attributes (i.e. `[:to_h, :errors, :method_missing]`)

Already this feels hacky, and I think that Github would have included an 'attributes' method or something so I don't have to check against public methods. However, to even attempt doing this on my query which has (a lot) of objects returned requires recursion and is currently breaking in an ugly fashion.

Below I'll show the current state of that code.

However, my main question here: **is there a simpler way to accomplish this?**

```ruby
def self.recursive_graphql_attributes(input)
  (input.public_methods - Object.public_methods).reject do |elem|
    [:to_h, :errors, :method_missing].include?(elem) || elem.to_s.include?('?')
  end.map do |elem|
    if ![String, NilClass, FalseClass, TrueClass].include? input.send(elem).class
      recursive_graphql_attributes(input.send(elem))
    else
      "#{elem.to_s.humanize}: #{input.send(elem)}"
    end
  end
end
```
Thanks much for your time and for putting together this fantastic  gem!!

**Comment by jturkel** [comment]
The format is a bit different but we implemented debug logging of query responses with something like:

```ruby
Rails.logger.debug { "GraphQL Response: #{response.to_h.to_json}" }
```

**Comment by Schwad** [comment]
@jturkel - I think this is exactly what I was looking for. Obviously I was off on another tangent but this achieves what I need. Thank you ! :)
