### ISSUE TITLE
key not found: "data" (KeyError)

### ISSUE THREAD

**Issue by afuno** [github/graphql-client#243]
Yesterday at some point I started getting this error when deploying to a server:

```
/tmp/build/vendor/bundle/ruby/2.6.0/gems/graphql-1.10.5/lib/graphql/schema/loader.rb:16:in `fetch': key not found: "data" (KeyError)
```

[View the entire log](https://pastebin.com/raw/qNPeksei)

I have not changed any files associated with this gem. But I updated the graphql gem to version 1.10.5. And also manually rolled it back to version 1.10.4. It was obvious, but I had to check it - the problem is not in the graphql gem version.

_The second application that is being requested is working. A working version of the first application (which as a client; about which I'm writing this issue) successfully receives responses from the second application._

The problem appeared in the area where the config/initializers/carrierwave.rb file changed. But it is also unclear how this file could break anything for graphql. This is hardly the reason.

But more (judging by the history of git commits), I did nothing. I do deployments quite often and there has never been such an error.

**Comment by afuno** [comment]
I also got the second kind of error:

```
/tmp/build/vendor/bundle/ruby/2.6.0/gems/graphql-client-0.16.0/lib/graphql/client/http.rb:59:in `execute': undefined method `request_uri' for #<URI::Generic /> (NoMethodError)
```

[View the entire log](https://pastebin.com/raw/Dn3V8zAJ)

**Comment by TeaBag477** [comment]
@afuno, hi how did you fix it ?)
