### ISSUE TITLE
Support @defer

### ISSUE THREAD

**Issue by josh** [github/graphql-client#34]
This is an early concept for supporting `@defer` in graphql-client. We'd still need upstream support on graphql-ruby so this probably won't be tackled very soon. Also `@defer` and `@stream` are barely standardized.

https://dev-blog.apollodata.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07

Though `@defer` was originally geared towards client side optimizations, I think it still has utility in a server side context where the client is building up a streaming response.

**Traditional Rails**

Take the following example non-GraphQL Rails example:

``` ruby
if repository.pull_requests.find(params[:id])
  render stream: true
else
  head :not_found
end
```

``` erb
<h1><%= pull_request.title %><h1>
<% pull_request.comments.each do |comment| %>
  <%= comment.body %>
<% end %>
```

Because ActiveRecord loads are lazy by default, this code works well generating an HTTP streaming response. We first do a quick check to see if the Pull Request exists, then start sending a 200 OK response to the browser. Entering the template, the title is already in memory so that initial markup can be sent to the browser. Then we hit our lazy comment loader which may take a bit to fetch all the comments and start writing those to the browser finishing the document. You can see we're able to start sending data to the browser pretty early.

**GraphQL Client now**

So lets look at the GraphQL version.

``` graphql
query PullRequestQuery($id: ID!) {
  pullRequest(id: $id) {
    id
    title
    comments {
      body
    }
  }
}
```

``` ruby
response = query(PullRequestQuery, id: params[:id])

if response.pull_request
  render stream: true
else
  head :not_found
end
```

``` erb
<h1><%= pull_request.title %><h1>
<% pull_request.comments.each do |comment| %>
  <%= comment.body %>
<% end %>
```

We did the right thing and combined all our requirements into a single GraphQL query that gets executed at the start of the request. This will likely be alot smart about fetching the data internally, but that means we're waiting for all the data before we can start generating a response to the client.

**GraphQL Client with `@defer` and `@stream`**

``` graphql
query PullRequestQuery($id: ID!) {
  pullRequest(id: $id) {
    id
    title @defer
    comments @stream {
      body
    }
  }
}
```

``` ruby
response = query(PullRequestQuery, id: params[:id])

if response.pull_request
  render stream: true
else
  head :not_found
end
```

``` erb
<h1><%= pull_request.title %><h1>
<% pull_request.comments.each do |comment| %>
  <%= comment.body %>
<% end %>
```

Nearly the same code as before, but using `@defer` and `@stream` in our GraphQL query.

Instead of getting a fully buffered response back, we'd receive a data stream like:

``` json
{
  "data": {
    "pullRequest": {
      "id": 123
    }
  }
}
```

``` json
{
  "path": ["pullRequest", "title"],
  "data": "Add support for @defer"
}
```

``` json
{
  "path": ["pullRequest", "comments", 0],
  "data": {
    "body": "Yeah, love that idea."
  }
}
```

``` json
{
  "path": ["pullRequest", "comments", 1],
  "data": {
    "body": "+1"
  }
}
```

As soon as the first main chunk is received, we can start to return a response. We know the pull request exists so we can properly set a 200 OK response code. Then we enter the template.

Now we hit `pull_request.title`. If the second chunk hasn't be received, we block here and wait for it. Then continue the view render streaming back content to the browser. Then we hit `pull_request.comments`. Again, if next chunk has be received we keep rendering until we block on receiving a data chunk.

This demonstrates an implicit wait on unfetched data. Its nice that are template code stays the same regardless of `@stream` or `@defer`.

An alternative API might be having fields marked as `@defer` return a `Promise` instead.

<hr>

To: @rmosolgo @charliesome @kdaigle @brandonblack @aroben

**Comment by rmosolgo** [comment]
🎉  such a cool idea. 

I'm trying to think through what's needed _beyond_ the [experimental graphql-ruby branch](https://github.com/rmosolgo/graphql-ruby/pull/168) to support this. (Merging that branch isn't a reality anytime soon, but it's my jumping-off point.)

For example, that branch works through `@defer`s, _pushing_ them to `context[:collector]`. I don't think it would work out-of-the-box because _this_ use-case wants to _pull_ data from the query (rather than receiving pushes). So by default, it would still work through all the defers before the `render` call, then there's nothin' gained! Does that sound right, have I understood that issue correctly?

**Comment by josh** [comment]
> I don't think it would work out-of-the-box because this use-case wants to pull data from the query

Well, that actually may work fine for GitHub's in-process use case. When we hit an unfetched field, we'll context switch back to the GraphQL resolver to pull the next patch. Our current in-process model limits true parallelize. We'll need to wait till we have some true process isolation before we can consider using a GraphQL stream response parser. Someday! Until then graphql-client can implement it and make a fun demo.

**Comment by josh** [comment]
Someday... 🍹
