### ISSUE TITLE
Client variable validation

### ISSUE THREAD

**Issue by josh** [github/graphql-client#43]
Would be great if the client could validate a set of variables before any remote requests are made.

``` ruby
FooQuery = Client.parse <<-'GRAPHQL'
  query($bar: String!) { }
GRAPHQL

# expected bar to be a String, but was null
client.validate_variables(FooQuery, variables: { bar: nil })

# expected bar to be a String, but was Int
client.validate_variables(FooQuery, variables: { bar: 123 })

# OK
client.validate_variables(FooQuery, variables: { bar: "123" })
```

Not sure what the ideal control flow would be. Maybe it returns a `ValidationErrors`-like object? I would rather not raise an exception.

@rmosolgo I think I can use the `Graph::Query` validation code without executing anything here, right?

**Comment by rmosolgo** [comment]
Yeah, the error messages aren't super awesome but ... it's there 😅 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/variables.rb#L11

**Comment by josh** [comment]
Dup of https://github.com/github/graphql-client/issues/73
