### ISSUE TITLE
skip/include precompilation 

### ISSUE THREAD

**Issue by josh** [github/graphql-client#61]
Mostly an idea at this point. Haven't totally thought it through.

But `@skip` and `@unless` directives could be statically compiled by the client rather than having the server conditionally process them.

**Variables**

``` ruby
MyQuery = Client.parse <<-'GRAPHQL'
query myQuery($someTest: Boolean) {
  experimentalField @include(if: $someTest)
}
GRAPHQL

def show
  Client.query(MyQuery, variables: { someTest: params[:someTest] })
end
```

**Precompiled**

``` ruby
MyQuery = Client.parse <<-'GRAPHQL'
query myQuery($someTest: Boolean) {
  experimentalField @include(if: $someTest)
}
GRAPHQL
MyQueryWithExperiments = MyQuery.curry(someTest: true)
MyQueryWithoutExperiments = MyQuery.curry(someTest: false)

def show
  query = params[:someTest] ? MyQueryWithExperiments : MyQueryWithoutExperiments
  Client.query(query)
end
```

##

CC: @tberman

**Comment by rmosolgo** [comment]
:thinking:

**Comment by rmosolgo** [comment]
On the one hand, you can imagine adding a filter to [`GraphQL::Language::Generation.generate`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/language/generation.rb#L18). But on the other hand, that code currently has no awareness of anything beyond the AST, so it would require some work to apply query variable values to the filter.

**Comment by josh** [comment]
Someday... maybe.
