### ISSUE TITLE
Add "is kind" helper

### ISSUE THREAD

**Issue by josh** [github/graphql-client#69]
Add a helper that can check object type, as well as interfaces.

Checking the exact type is already possible with `typename`

``` ruby
user.instance_of?(::User)
user.typename == "User"
```

But there is nothing like `is_a` or `kind_of` that can check the type hierarchy.

 ``` ruby
user.is_a?(::User)
user.is_a?(::Author)
```

**Comment by josh** [comment]
Looking for naming suggestions. I can't call it `is_a` or `kind_of` since those are Ruby builtins. Maybe `type_of?`

**Comment by josh** [comment]
CC @mclark

**Comment by mclark** [comment]
:+1: for `type_of?`. It's consistent with the rest of the GraphQL vocabulary anyway.

**Comment by rmosolgo** [comment]
Another option would be `of_type?`, personally that makes a bit more sense to me, eg 

```ruby
user.of_type?(User)
user.of_type?(Author)
```

At least for me, that's how I say it in plain talk, "object O is of type T"
