### ISSUE TITLE
class_eval undefined if rails isn't loaded

### ISSUE THREAD

**Issue by mcolyer** [github/graphql-client#9]
If you invoke `GraphQL::Client::HTTP` with [a block](https://github.com/github/graphql-client/blob/cd56478c90bf9748f2221c940af6d24de79f80f6/lib/graphql/client/http.rb#L32), `NoMethodError: undefined method 'class_eval'` is thrown.

Oddly this doesn't occur if the rails gem is loaded into the environment.

**Comment by josh** [comment]
> Oddly this doesn't occur if the rails gem is loaded into the environment.

Ah, I think we're implicitly depending on https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/kernel/singleton_class.rb#L3

**Comment by josh** [comment]
Thanks!
