### ISSUE TITLE
Warning "Coercing without a context is deprecated"

### ISSUE THREAD

**Issue by alexander-myltsev** [github/graphql-client#90]
I am having warning as follows `Coercing without a context is deprecated; use 'coerce_isolated_input' if you don't want context-awareness` while using version `0.8.0`. There is some info on the topic [here](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md).

How should I resolve the warning?

**Comment by rmosolgo** [comment]
I think this call needs a change:  https://github.com/github/graphql-client/blob/master/lib/graphql/client/query_result.rb#L122

```diff 
- @type.coerce_input(value)
+ @type.coerce_isolated_input(value)
```

**Comment by rmosolgo** [comment]
But, I guess it's a bit more subtle than that, since older versions of the gem don't have that method 😖
