### ISSUE TITLE
Incorporate Relay Modern <ModuleName>_<propName> naming convention

### ISSUE THREAD

**Issue by josh** [github/graphql-client#94]
The new modern Relay APIs are moving towards a naming convention for mapping fragments to prop names (local assigns in ERB).

> A naming convention of `<file name>_<prop name>` for fragments is advised. This restriction is required while migrating from classic to modern APIs to allow for cross-compatibility.

https://facebook.github.io/relay/docs/FragmentContainer.html

``` graphql
fragment TodoItem_item on Todo {
  text
  isComplete
}
```

In this case, we expect `item` to be the prop name for this data.

If we want to start inferring local assign names, aligning to this pattern would ensure Relay interop in the future. https://github.com/github/graphql-client/pull/86

##

CC: @nakajima @arthurschreiber @mclark @tma

**Comment by josh** [comment]
Hmm, this actually might not be super necessary for graphql-cilent itself as we have module namespaces. It appears that Relay uses a flat namespace for all fragments (kinda lame). While we automatically namespace fragments based on module name. In effect, we just handle this naming convention automatically.

Maybe the internal generated fragment names could be aligned closer to what Relay is using. I wonder how it joins directories.

**Comment by tma** [comment]
Apologize for stating the obvious ✌️: `TodoItem_item` feels wrong 🙈.

**Comment by josh** [comment]
Closing as this doesn't make apply to graphql-client as we have *real* namespaces.
