### ISSUE TITLE
undefined method `filter_by_path` for ...

### ISSUE THREAD

**Issue by robinmonjo** [github/graphql-client#96]
Hello all,

I have a crash at [this line](https://github.com/github/graphql-client/blob/master/lib/graphql/client/query_result.rb#L111) while querying a graphql api:

Query:

````
mutation($name: String!) {
  addSomeObject(input: {name: $name}) {
    clientMutationId
      errors
      someObject {
        id,
        name
      }
    }
}
````

Response:

````
{
  "data": {
    "addSomeObject": {
      "clientMutationId": null,
      "errors": [
        "Name is already taken"
      ]
    }
  }
}
````
And the error is:

````
NoMethodError:
       undefined method `filter_by_path' for ["Name is already taken"]:GraphQL::Client::List
````

Not sure if I'm doing something wrong or if it's a bug ....

**Comment by josh** [comment]
Oh, `errors` is a special property in graphql-client.

https://github.com/github/graphql-client/blob/master/guides/handling-errors.md

A workaround would be to alias it to something else in your query:

``` graphql
mutation($name: String!) {
  addSomeObject(input: {name: $name}) {
    clientMutationId
      whateverErrors: errors
      someObject {
        id,
        name
      }
    }
}
```

**Comment by robinmonjo** [comment]
Thank you very much for your answer, still new to graphql. Will try the alias and plan to correct the API according to the spec you linked 👍
